services:
    exam-mariadb:
        image: mariadb:10.6.20
        env_file: .env
        volumes:
            - mariadb_data:/var/lib/mysql
        ports:
            - 3306:3306

    exam-arangodb:
        image: arangodb:latest
        env_file: .env
        ports:
            - "8529:8529"
        volumes:
            - arango_data:/var/lib/arangodb3
        networks:
            - arango-network

    exam-phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - exam-mariadb
        env_file: .env
        ports:
            - 8080:80

volumes:
    mariadb_data:
    arango_data:

networks:
    arango-network:
        driver: bridge
