services:
  mariadb:
    image: mariadb:10.6.20
    container_name: databases-exam_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: databases-exam
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306

  arangodb-databases:
    image: arangodb:latest
    environment:
      - ARANGO_ROOT_PASSWORD=password
    ports:
      - "8529:8529"
    volumes:
      - arango_data:/var/lib/arangodb3
    networks:
      - arango-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: databases-exam_phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8080:80

volumes:
  mariadb_data:
  arango_data:

networks:
  arango-network:
    driver: bridge
