services:
    exam-mariadb:
        image: mariadb:10.6.20
        environment:
            MYSQL_DATABASE: databases-exam
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - mariadb_data:/var/lib/mysql
        ports:
            - 3306:3306

    exam-arangodb:
        image: arangodb:latest
        environment:
            ARANGO_ROOT_PASSWORD: password
        ports:
            - "8529:8529"
        volumes:
            - arangodb_data:/var/lib/arangodb3
        networks:
            - arango-network

    exam-phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - exam-mariadb
        environment:
            PMA_HOST: exam-mariadb
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 8080:80

volumes:
    mariadb_data: {}
    arangodb_data: {}
networks:
    arango-network:
        driver: bridge
